from pathlib import Path

def write_full_answer_html(proof_dir: Path) -> None: ...
def make_bilingual_mirror_question_duplicate(proof_dir: Path) -> None: ...
def make_coding_answer_hint_only(proof_dir: Path) -> None: ...
def make_duplicate_ledger_question_id(proof_dir: Path) -> None: ...
def make_duplicate_inventory_question_id(proof_dir: Path) -> None: ...
def make_generic_visual_fallback_answer(proof_dir: Path) -> None: ...
def make_high_mark_illustration_answer_without_steps(proof_dir: Path) -> None: ...
def make_ledger_question_text_drift(proof_dir: Path) -> None: ...
def make_nested_paper_reports_ledger(proof_dir: Path) -> None: ...
def make_nested_duplicate_ledger_question_id(proof_dir: Path) -> None: ...
def make_option_only_answer_without_choices(proof_dir: Path) -> None: ...
def make_placeholder_question_text(proof_dir: Path) -> None: ...
def make_placeholder_learner_html(proof_dir: Path) -> None: ...
def make_question_inventory_order_drift(proof_dir: Path) -> None: ...
def make_raw_child_report_lacks_lane_findings(proof_dir: Path) -> None: ...
def make_visual_inspected_answer(proof_dir: Path) -> None: ...
def make_visual_inspected_unreadable(proof_dir: Path) -> None: ...
def make_stale_verifier_report(proof_dir: Path) -> None: ...
def make_unresolved_major_report(proof_dir: Path) -> None: ...
